plugins {
    id 'performance'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

performance {
    simulationClass = 'simulations.CCD_PerformanceRegression' // <---- SPECIFY YOUR SIMULATION HERE
    // simulations.CCD_PerformanceRegression",
    // simulations/DMStoreSimulation"
    // simulations/CreateUser"
    // simulations/CaseDocApiSimulation"
    // simulations/DMStoreSimulation"
}